'use strict';
const $=s=>document.querySelector(s), app=$('#app'), KEY='pico-panic-v1';
const names={move:['↗','ROBOT ROUTE','ロボを動かす'],pack:['▣','PACK & GO','荷物を入れる'],order:['▰','WORD BRIDGE','言葉で橋づくり'],clock:['◷','TIME TUNER','時計を合わせる'],cafe:['☕','CAFE MIX','注文をつくる'],reply:['♫','TALK BACK','会話を返す'],place:['⌖','CAT SPOT','位置に置く'],switch:['◉','CITY SIGNAL','街を切り替える']};
const items=[['🍎','apple'],['🍌','banana'],['📕','book'],['🔑','key'],['☂️','umbrella'],['🧢','cap']];
const DB=[]; const add=(kind,rows)=>rows.forEach((r,i)=>DB.push({kind,id:kind+i,...r}));
add('move',[
['Go left.',[3], 'left は左。Go left. は「左へ進んで」。'],['Go right.',[5],'right は右。道案内にも使います。'],['Go up.',[1],'up は上。画面の上へ動かします。'],['Go down.',[7],'down は下。'],['Go left, then up.',[3,0],'then は「それから」。左→上の順です。'],['Go right, then down.',[5,8],'right → down の順に動きます。'],['Go up, then right.',[1,2],'up → right。then で順番をつなぎます。'],['Go down, then left.',[7,6],'down → left。指示の順に移動します。']].map(([prompt,path,why])=>({prompt,path,answer:prompt,why,hint:'矢印をタップ。中央から指示の順に移動'})));
add('pack',[
['Pack a book.',[2]],['Pack an umbrella.',[4]],['Pack a key.',[3]],['Pack a cap.',[5]],['Pack an apple and a banana.',[0,1]],['Pack a book and a key.',[2,3]],['Pack a cap and an umbrella.',[5,4]],['Pack an apple and a book.',[0,2]]].map(([prompt,want])=>({prompt,want,answer:want.map(i=>items[i][1]).join(' + '),why:'Pack は「荷物に入れる」。and でつながれた物を両方入れます。a / an はここでは1つ。',hint:'品物をタップしてバッグへ。もう一度で戻す'})));
add('order',[
['I like coffee.','私はコーヒーが好きです。'],['She is my friend.','彼女は私の友達です。'],['Where is the station?','駅はどこですか。'],['I can swim.','私は泳げます。'],['I need some water.','私は水が少し必要です。'],['Do you like music?','音楽は好きですか。'],['This is my bag.','これは私のバッグです。'],['We are very happy.','私たちはとても幸せです。']].map(([answer,ja])=>({prompt:ja,answer,words:answer.replace(/[.?]/g,'').split(' '),why:answer.startsWith('Do')?'Do + 主語 + 動詞で、一般動詞の疑問文に。':answer.startsWith('Where')?'Where + is + 場所を知りたい物、の順です。':answer.startsWith('Please')?'Please + 動詞で丁寧にお願いできます。':'主語の次に動詞を置き、残りの内容を続けます。',hint:'単語を順にタップして橋を作る。橋の単語で戻す'})));
add('clock',[[3,0,'three o’clock'],[7,0,'seven o’clock'],[9,30,'half past nine'],[2,30,'half past two'],[5,15,'quarter past five'],[10,15,'quarter past ten'],[4,45,'quarter to five'],[11,45,'quarter to twelve']].map(([hour,minute,word])=>({prompt:`Set ${word}.`,hour,minute,answer:`${hour}:${String(minute).padStart(2,'0')}`,why:word.includes('to')?'quarter to は次の時刻の15分前です。':word.includes('half')?'half past は30分過ぎ。':word.includes('quarter')?'quarter past は15分過ぎ。':'o’clock は「〜時ちょうど」。',hint:'時と分をタップで合わせ、「決定」'})));
add('cafe',[[1,0],[2,0],[1,1],[2,1],[1,2],[2,2],[3,0],[3,1]].map(([coffee,milk])=>({prompt:`${['','One','Two','Three'][coffee]} coffee${coffee>1?'s':''}, ${milk?['','one milk','two milks'][milk]:'no milk'}.`,coffee,milk,answer:`コーヒー ${coffee} / ミルク ${milk}`,why:'one / two / three は1 / 2 / 3。no milk はミルクなし。ここでは飲み物の注文数です。',hint:'＋と−で注文数をそろえて提供'})));
add('reply',[
['Thank you!',['You’re welcome!','Good night!','I’m sorry.'],0,'お礼には You’re welcome!（どういたしまして）。'],['How are you?',['It’s a pen.','I’m good, thanks.','See you!'],1,'調子を聞かれたら I’m good, thanks.（元気です、ありがとう）。'],['See you tomorrow!',['See you!','I’m hungry.','You’re welcome!'],0,'別れの See you. は「またね」。'],['I’m sorry.',['Good morning!','That’s okay.','I’m ten.'],1,'謝罪への That’s okay. は「大丈夫ですよ」。'],['Good morning!',['Good morning!','Good night!','Thanks anyway.'],0,'朝の挨拶には Good morning. と返せます。'],['Nice to meet you.',['Nice to meet you, too.','Not now.','Good night.'],0,'初対面の挨拶。too を加えると「こちらこそ」。'],['Would you like some tea?',['Yes, please.','You’re welcome.','See you.'],0,'勧められた物を受け取るときは Yes, please.。'],['Have a nice day!',['You too!','It’s red.','I’m sorry.'],0,'You too! は「あなたもね」。']].map(([prompt,options,correct,why])=>({prompt,options,correct,answer:options[correct],why,hint:'相手のひと言に、自然な返事を送る',audio:true})));
add('place',[
['above',1,'上'],['below',7,'下'],['to the left of',3,'左'],['to the right of',5,'右'],['in',4,'中'],['above',1,'上'],['below',7,'下'],['in',4,'中']].map(([prep,target,ja],i)=>({prompt:`Put the ${i<4?'cat':'key'} ${prep} the box.`,target,icon:i<4?'🐈':'🔑',answer:`箱の${ja}`,why:`${prep} は「${ja}に」。物と箱の位置関係を表します。`,hint:'置きたい場所をタップ。位置を選んで「決定」'})));
add('switch',[
['Turn on the light.',[true,false,false]],['Turn off the light.',[false,false,false]],['Open the gate.',[false,true,false]],['Close the gate.',[false,false,false]],['Start the fan.',[false,false,true]],['Stop the fan.',[false,false,false]],['Open the gate and turn on the light.',[true,true,false]],['Start the fan and open the gate.',[false,true,true]]].map(([prompt,want],i)=>({prompt,want,initial:i===1?[true,false,false]:i===3?[false,true,false]:i===5?[false,false,true]:[false,false,false],answer:`照明 ${want[0]?'ON':'OFF'} / 門 ${want[1]?'開':'閉'} / ファン ${want[2]?'ON':'OFF'}`,why:'turn on / off は入れる・消す、open / close は開く・閉じる、start / stop は動かす・止める。指示のない物はそのまま。',hint:'スイッチを切り替える。指示のない物は変えない'})));
let saved={version:1,slow:false,sound:true,reduce:matchMedia('(prefers-reduced-motion: reduce)').matches,practiced:false,best:0};
try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.version===1){for(const k of ['slow','sound','reduce','practiced'])if(typeof v[k]==='boolean')saved[k]=v[k];if(Number.isFinite(v.best)&&v.best>=0)saved.best=Math.min(v.best,999999)}}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{}}
const shuffle=a=>a.map(v=>({v,r:Math.random()})).sort((a,b)=>a.r-b.r).map(x=>x.v);let S=null,raf=0,audio=null,voiceOK=false,speechSeq=0;
function header(){return `<header class="top"><div class="brand">PICO <em>PANIC</em><span style="font-size:12px;letter-spacing:1px;margin-left:9px">ENGLISH ARCADE</span></div><span class="pill">PLAY · LEARN · REPEAT</span></header>`}
function sound(ok){if(!saved.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=ok?660:180;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.start();o.stop(audio.currentTime+.17)}catch{}}
function cancelSpeech(){speechSeq++;try{speechSynthesis.cancel()}catch{}}
function prime(){sound(true);voiceOK=saved.sound&&'speechSynthesis'in window&&typeof SpeechSynthesisUtterance!=='undefined'&&speechSynthesis.getVoices().some(v=>/^en[-_]/i.test(v.lang));}
function speak(q){if(!q.audio||!saved.sound||!voiceOK)return;const seq=++speechSeq;const u=new SpeechSynthesisUtterance(q.prompt);u.lang='en-US';u.rate=.85;u.voice=speechSynthesis.getVoices().find(v=>/^en[-_]/i.test(v.lang))||null;u.onstart=()=>{if(seq===speechSeq&&S?.phase==='active'){$('#speechnote').textContent='音声＋文字で出題';}};u.onerror=()=>{if(seq===speechSeq){voiceOK=false;const n=$('#speechnote');if(n)n.textContent='音声を使えないため、文字で出題';}};try{speechSynthesis.speak(u)}catch{voiceOK=false}}
function home(){document.body.classList.remove('playing');cancelAnimationFrame(raf);cancelSpeech();S=null;document.body.classList.toggle('reduced',saved.reduce);app.innerHTML=header()+`<section class="home"><div class="intro"><div class="eyebrow">小さな英語、大きなひらめき。</div><h1>PICO<br><span>PANIC!</span></h1><p>英語を読んだら、すぐアクション。<br>運んで、動かして、つなげよう。</p><div class="actions"><button class="primary" id="start">${saved.practiced?'プレイする':'練習してスタート'}</button><button class="secondary" id="practice">練習だけ</button></div><div class="fine">約75秒 · 3ライフ · 最後はボス<br>ベスト ${saved.best} pt</div></div><div class="artwrap"><img class="heroart" src="hero.png" alt="オレンジのヘッドホンをつけたミント色のピコと、小さな四角い相棒"></div></section><div class="settings"><label><input type="checkbox" id="slow" ${saved.slow?'checked':''}>ゆっくり</label><label><input type="checkbox" id="sound" ${saved.sound?'checked':''}>音声・効果音</label><label><input type="checkbox" id="reduce" ${saved.reduce?'checked':''}>動きを減らす</label></div><div class="tiles">${Object.values(names).map(n=>`<div class="tile"><b>${n[0]}</b>${n[2]}</div>`).join('')}</div><p class="fine">タップだけで遊べます。音声OFFでも全文を表示。<br>記録はこのブラウザに保存されます。学習効果を保証するものではありません。</p>`;$('#start').onclick=()=>{prime();start(saved.practiced?'run':'intro')};$('#practice').onclick=()=>{prime();start('practice')};for(const k of ['slow','sound','reduce'])$('#'+k).onchange=e=>{saved[k]=e.target.checked;persist();document.body.classList.toggle('reduced',saved.reduce)}}
function start(mode,ids){cancelSpeech();cancelAnimationFrame(raf);const pool=ids?ids.map(id=>DB.find(q=>q.id===id)).filter(Boolean):[];S={mode,phase:'active',life:3,score:0,combo:0,maxCombo:0,results:[],total:0,t:0,last:performance.now(),q:null,deck:[],pool,round:0,boss:false,bossStep:0,practiceQueue:['move0','pack0','order0'],generation:0};next();raf=requestAnimationFrame(tick)}
function selectQ(){if(S.mode==='intro'||S.mode==='practice'){const id=S.practiceQueue.shift();return DB.find(q=>q.id===id)}if(S.mode==='retry')return S.pool.shift();if(S.total>=60&&!S.boss){S.boss=true;S.bossStep=0}if(S.boss){if(S.bossStep>=3)return null;const step=S.bossStep++;let id=['pack5','move4','order3'][step];if(S.q?.id===id)id=['pack6','move5','order4'][step];return DB.find(q=>q.id===id)}if(!S.deck.length){const kinds=shuffle(Object.keys(names));if(kinds[0]===S.q?.kind)[kinds[0],kinds[1]]=[kinds[1],kinds[0]];S.deck=kinds.map(k=>{const choices=DB.filter(q=>q.kind===k&&!S.results.slice(-16).some(r=>r.id===q.id));return shuffle(choices.length?choices:DB.filter(q=>q.kind===k))[0]})}return S.deck.shift()}
function practiceMode(){return ['intro','practice'].includes(S.mode)}
function next(){cancelSpeech();const q=selectQ();if(!q){finish();return}S.q=q;S.round++;S.generation++;S.phase='active';S.t=0;S.limit=S.mode==='intro'||S.mode==='practice'?Infinity:S.mode==='retry'?16:S.boss?7:Math.max(saved.slow?9:5,(saved.slow?13:9)-Math.floor(S.total/20)*2);if(!practiceMode()&&['clock','order','cafe'].includes(q.kind))S.limit+=2;S.input={pos:4,path:0,pack:[],words:[],hour:12,minute:0,coffee:0,milk:0,place:null,switches:[...(q.initial||[])]};render();speak(q)}
function render(){document.body.classList.add('playing');const q=S.q,n=names[q.kind],practice=['intro','practice'].includes(S.mode);app.innerHTML=header()+`<div class="hud"><span class="pill">${practice?'PRACTICE':S.mode==='retry'?'RETRY':S.boss?'BOSS '+S.bossStep+'/3':'LEVEL '+Math.min(3,1+Math.floor(S.total/20))}</span><span>${S.score} pt · ${S.combo} COMBO</span><span class="hearts" aria-label="残り${S.life}ライフ">${'♥'.repeat(S.life)}${'♡'.repeat(3-S.life)}</span><button class="secondary" id="pause" aria-label="一時停止">Ⅱ</button></div><div class="timer" aria-label="残り時間"><i id="bar" style="width:100%"></i></div><section class="stage ${S.boss?'boss':''}" data-kind="${q.kind}"><div class="stagehead"><span>${n[0]} ${n[1]}</span><span id="seconds">${practice?'時間制限なし':Math.ceil(S.limit)+'秒'}</span></div><div class="prompt">${q.prompt}</div><p class="hint">${q.hint}</p><div class="gamearea" id="area"></div></section><div class="bottom"><p>${practice?'まずは3ゲーム。失敗しても練習できます。':S.mode==='retry'?'間違えた問題だけ、もう一度。':S.boss?'3つのミッションを突破しよう！':`ボスまで ${Math.max(0,Math.ceil(60-S.total))} 秒`}</p><span class="fine">${saved.sound?'SOUND ON':'SOUND OFF'}</span></div>`;$('#pause').onclick=pause;renderArea();}
function btn(label,act,cls='object'){return `<button class="${cls}" data-act="${act}">${label}</button>`}
function renderArea(){const q=S.q,i=S.input;let h='';switch(q.kind){case'move':h=`<div class="grid">${Array.from({length:9},(_,k)=>`<div class="object" style="text-align:center;background:${i.pos===k?'#c1ff64':'#ffffff80'}"><span class="robot">${i.pos===k?'◉':'·'}</span></div>`).join('')}</div><div class="arrowpad"><span></span>${btn('↑','move:-3')}<span></span>${btn('←','move:-1')}${btn('↓','move:3')}${btn('→','move:1')}</div>`;break;
case'pack':h=`<div class="tray" aria-label="バッグ">${i.pack.length?i.pack.map(k=>btn(items[k][0],'pack:'+k)).join(''):'BAG · バッグ'}</div><div class="options">${items.map((a,k)=>btn(`<span class="icon" role="img" aria-label="${['りんご','バナナ','本','鍵','傘','帽子'][k]}">${a[0]}</span>`, 'pack:'+k,'object'+(i.pack.includes(k)?' selected':''))).join('')}</div>${btn('荷造り完了','submit','primary')}`;break;
case'order':if(!i.available)i.available=shuffle(q.words.map((w,k)=>({w,k})));h=`<div class="tray" aria-label="作った文">${i.words.map(k=>btn(q.words[k],'word:'+k)).join('')||'START ━━━━━━━━━ GOAL'}</div><div class="options">${i.available.filter(a=>!i.words.includes(a.k)).map(a=>btn(a.w,'word:'+a.k)).join('')}</div>${btn('橋を渡る','submit','primary')}`;break;
case'clock':h=`<div class="dial"><i class="hand hour" style="transform:rotate(${i.hour*30+i.minute/2}deg)"></i><i class="hand minute" style="transform:rotate(${i.minute*6}deg)"></i></div><div class="readout">${i.hour}:${String(i.minute).padStart(2,'0')}</div><div class="options">${btn('時 −','hourBack')}${btn('時 ＋','hour')}${btn('分 ＋15','minute')}${btn('決定','submit','primary')}</div>`;break;
case'cafe':h=`${['coffee','milk'].map((k,j)=>`<div class="options" style="align-items:center"><span style="font-size:30px">${j?'🥛':'☕'}</span>${btn('−',k+':-1')}<span class="count">${i[k]}</span>${btn('＋',k+':1')}</div>`).join('')}${btn('提供する','submit','primary')}`;break;
case'reply':h=`<div class="bubble">◉ 「${q.prompt}」</div><span class="fine" style="color:#526174" id="speechnote">${voiceOK&&saved.sound?'音声＋文字で出題':'文字で出題'}</span><div class="options">${q.options.map((a,k)=>btn(a,'reply:'+k)).join('')}</div>${voiceOK&&saved.sound?btn('もう一度聞く','listen','secondary'):''}`;break;
case'place':h=`<div class="location">${Array.from({length:9},(_,k)=>k===4?btn(i.place===k?q.icon:'BOX','place:'+k,'object box'):btn(i.place===k?q.icon:['','上','','左','','右','','下',''][k]||'·','place:'+k,'object'+(i.place===k?' selected':''))).join('')}</div>${btn('ここに置く','submit','primary')}`;break;
case'switch':h=`<div class="switches">${['照明','門','ファン'].map((v,k)=>btn(`${['💡','▥','✣'][k]}<br>${v}<br>${k===1?(i.switches[k]?'開':'閉'):(i.switches[k]?'ON':'OFF')}`,'switch:'+k,'object'+(i.switches[k]?' on':''))).join('')}</div>${btn('決定','submit','primary')}`;break;}
$('#area').innerHTML=h;const gen=S.generation;document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{if(!S||S.phase!=='active'||S.generation!==gen)return;act(b.dataset.act)})}
function act(a){if(!S||S.phase!=='active')return;if(S.t+Math.min((performance.now()-S.last)/1000,.25)>S.limit){resolve(false,true);return}const [what,value]=a.split(':'),v=Number(value),q=S.q,i=S.input;if(what==='listen'){cancelSpeech();speak(q);return}if(what==='move'){const next=i.pos+v;if(next<0||next>8||(v===-1&&i.pos%3===0)||(v===1&&i.pos%3===2))return;if(next!==q.path[i.path]){resolve(false);return}i.pos=next;i.path++;if(i.path===q.path.length){renderArea();resolve(true);return}}
if(what==='pack'){i.pack=i.pack.includes(v)?i.pack.filter(k=>k!==v):[...i.pack,v]}
if(what==='word'){const idx=i.words.indexOf(v);i.words=idx>=0?i.words.slice(0,idx):[...i.words,v]}
if(what==='hourBack')i.hour=(i.hour+10)%12+1;if(what==='hour')i.hour=i.hour%12+1;if(what==='minute')i.minute=(i.minute+15)%60;
if(what==='coffee'||what==='milk')i[what]=Math.max(0,Math.min(3,i[what]+v));if(what==='place')i.place=v;if(what==='switch')i.switches[v]=!i.switches[v];
if(what==='reply'){resolve(v===q.correct);return}if(what==='submit'){let ok=false;if(q.kind==='pack')ok=i.pack.length===q.want.length&&q.want.every(k=>i.pack.includes(k));if(q.kind==='order')ok=i.words.map(k=>q.words[k]).join(' ')===q.words.join(' ');if(q.kind==='clock')ok=i.hour===q.hour&&i.minute===q.minute;if(q.kind==='cafe')ok=i.coffee===q.coffee&&i.milk===q.milk;if(q.kind==='place')ok=i.place===q.target;if(q.kind==='switch')ok=q.want.every((b,k)=>b===i.switches[k]);resolve(ok);return}renderArea()}
function resolve(ok,timeout=false){if(!S||S.phase!=='active')return;S.phase='feedback';cancelSpeech();S.feedback=0;S.feedbackLength=ok?.8:2;S.results.push({...S.q,ok,timeout});if(ok){S.combo++;S.score+=100+Math.min(S.combo,10)*10;S.maxCombo=Math.max(S.combo,S.maxCombo)}else{S.combo=0;if(!['intro','practice','retry'].includes(S.mode))S.life--}sound(ok);const el=document.createElement('div');el.className='feedback '+(ok?'':'bad');el.setAttribute('role','status');el.innerHTML=`<strong>${ok?'NICE!':timeout?'TIME UP':'OOPS!'}</strong><p>${ok?S.combo+' COMBO':S.q.answer}</p>${ok?'':`<div>${S.q.why}</div>`}`;$('.stage').append(el)}
function tick(now){if(!S)return;let dt=Math.min((now-S.last)/1000,.25);S.last=now;if(S.phase==='active'){S.t+=dt;if(S.mode==='run'&&!S.boss)S.total+=dt;if(S.t>=S.limit)resolve(false,true);const bar=$('#bar');if(bar)bar.style.width=(Number.isFinite(S.limit)?Math.max(0,100*(1-S.t/S.limit)):100)+'%';if($('#seconds'))$('#seconds').textContent=Number.isFinite(S.limit)?Math.max(0,Math.ceil(S.limit-S.t))+'秒':'時間制限なし'}else if(S.phase==='feedback'){S.feedback+=dt;if(S.mode==='run'&&!S.boss)S.total+=dt;if(S.feedback>=S.feedbackLength){if(S.life<=0)finish();else next()}}if(S&&S.phase!=='done')raf=requestAnimationFrame(tick)}
function pause(){if(!S||!['active','feedback'].includes(S.phase))return;S.beforePause=S.phase;S.phase='paused';cancelSpeech();const el=document.createElement('div');el.className='overlay';el.innerHTML=`<div class="modal"><div class="eyebrow">PAUSED</div><h2>ひと息いれよう。</h2><p>時間は止まっています。</p><div class="actions"><button class="primary" id="resume">つづける</button><button class="secondary" id="quit">終了して復習</button></div></div>`;app.append(el);$('#resume').onclick=()=>{el.remove();S.phase=S.beforePause;S.last=performance.now()};$('#quit').onclick=finish}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('blur',()=>{if(document.hidden)pause()});
document.addEventListener('keydown',e=>{if(!S||S.phase!=='active'||S.q.kind!=='move')return;const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-3,ArrowDown:3}[e.key];if(d&&!e.repeat){e.preventDefault();act('move:'+d)}});
function finish(){document.body.classList.remove('playing');if(!S)return;cancelAnimationFrame(raf);cancelSpeech();S.phase='done';const results=S.results,miss=[...new Set(results.filter(r=>!r.ok).map(r=>r.id))],practice=['intro','practice'].includes(S.mode),intro=S.mode==='intro';if(practice)saved.practiced=true;else if(S.mode==='run')saved.best=Math.max(saved.best,S.score);persist();app.innerHTML=header()+`<section class="split"><div><div class="eyebrow">${practice?'READY TO PLAY':S.life===0?'NEXT TIME, PICO!':'ROUND COMPLETE'}</div><h2>${practice?'練習おつかれさま！':S.life===0?'ここから、覚えていこう。':'ナイスラン！'}</h2><div class="score">${S.score}<span style="font-size:22px;letter-spacing:0"> pt</span></div><p>${results.filter(r=>r.ok).length} / ${results.length} 正解 · 最大 ${S.maxCombo} コンボ</p></div><img class="miniart" src="hero.png" alt="ピコと相棒"></section><div class="actions"><button class="primary" id="again">${practice?'本番へ':'もう一度プレイ'}</button>${miss.length?'<button class="secondary" id="retry">間違いだけ再挑戦 ('+miss.length+')</button>':''}<button class="secondary" id="home">ホーム</button></div><h2 style="font-size:22px">${results.length?'今日のひらめきメモ':'まだ回答はありません'}</h2><div class="review">${results.map(r=>`<article class="${r.ok?'':'miss'}"><div class="fine">${r.ok?'✓ 正解':'↻ 復習'} · ${names[r.kind][2]}</div><strong>${r.prompt}</strong><p style="color:#e9f2fb">正解：${r.answer}</p><p>${r.why}</p></article>`).join('')}</div>`;$('#again').onclick=()=>{prime();start('run')};$('#home').onclick=home;if($('#retry'))$('#retry').onclick=()=>{prime();start('retry',miss)}}
home();

// Optional browser-agent read interface. Unsupported browsers remain unchanged.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'get_round_state',title:'Read PICO round',description:'Read current round status and score without revealing answers or changing play.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return S?{mode:S.mode,phase:S.phase,score:S.score,lives:S.life,round:S.round,game:S.q?.kind}:{phase:'home',best:saved.best}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
